### PR TITLE
Allow for longer file name lenght

### PR DESCRIPTION
**Pull request by guillaumevernieres**
**Description**
Increasing the hardwired allowable filename length from 128 to 1024.

### CODE REVIEW

**Comment by travissluka** [comment]
Seems harmless.... 
but I'm weary of diverging from fms code when it could be fixed in other ways. I'll look at the soca-science PR first and see if there is another way around it. Possible to pass in shorter relative paths instead of the long absolute paths?

**Comment by guillaumevernieres** [comment]
> Seems harmless....
> but I'm weary of diverging from fms code when it could be fixed in other ways. I'll look at the soca-science PR first and see if there is another way around it. Possible to pass in shorter relative paths instead of the long absolute paths?

I thought about that, but 128 is lamely small ...

**Comment by danholdaway** [comment]
I get around this by always having things in Data/ with some short names for the files and then always running in the same directory as Data/. I agree that the change should be made in FMS but it's tricky. Right now our repo has conflicts with theirs due to different CMakeLists.txt. So it's a wait to find out if GFDL will take this and if they don't we will have diverged and you'd have to untangle on the SOCA side which could be more painful. So I think if you can fix on your side then great.

What we need to do is move FMS to modules or use their CMake but in the bundle (is that possible?). Then we can sync up and start pushing our changes regularly, as we do with FV3. Then you can have your branch merge into upstream instead and we'll find out fairly quickly. @aerorahul can we get FMS into jedi-stack? I think you mentioned doing it once. I'd be happy to see it gone from my builds.

**Comment by aerorahul** [comment]
@yes, there is a branch in jedi-stack and a closed PR.
It probably needs 30 mins of more work.

**Comment by aerorahul** [comment]
See [this](https://github.com/JCSDA/jedi-stack/pull/160) PR in jedi-stack.

**Comment by guillaumevernieres** [comment]
> I get around this by always having things in Data/ with some short names for the files and then always running in the same directory as Data/. I agree that the change should be made in FMS but it's tricky. Right now our repo has conflicts with theirs due to different CMakeLists.txt. So it's a wait to find out if GFDL will take this and if they don't we will have diverged and you'd have to untangle on the SOCA side which could be more painful. So I think if you can fix on your side then great.
> 
> What we need to do is move FMS to modules or use their CMake but in the bundle (is that possible?). Then we can sync up and start pushing our changes regularly, as we do with FV3. Then you can have your branch merge into upstream instead and we'll find out fairly quickly. @aerorahul can we get FMS into jedi-stack? I think you mentioned doing it once. I'd be happy to see it gone from my builds.



> See [this](https://github.com/JCSDA/jedi-stack/pull/160) PR in jedi-stack.

Yeah, but that doesn't address the issue ... 128 is too small. I'm happy untangling when the time come, but I doubt we would have to, puny change and I can't see why GFDL would object.

**Comment by aerorahul** [comment]
Agreed. The stack pr does not solve this particular issue. 
I don't see why gfdl will object to this change. 
Create an issue and open a PR in GFDL repo.

**Comment by travissluka** [comment]
@guillaumevernieres soca-science is using the full file path for input files, without moving or symlinking, due to reasons of laziness. It should be modified so that symlinks to the files are created in the working directory

**Comment by guillaumevernieres** [comment]
@travissluka not laziness, time optimization. Nothing wrong with a lengthy filename, we're not in the 70's anymore.
This pr fixes our problem now, are you saying we should spend a few extra hours in soca to fix the same problem in a different way? It's Saturday ... Seems like we're already stretched out in available time, and we've got a never ending list of other fish to fry! I'm happy pushing this to the stable branch, maybe do the same on the GFDL side and move on ... Job done. The alternative is a fix on the soca-sci side, which involves testing geos, ufs, mom6-sis2 and mom6solo, and only one of these models is currently ctested. That's currently a day of work.
Press the green clicky thing and let's work on more useful stuff.

**Comment by travissluka** [comment]
This should no longer be needed once https://github.com/JCSDA-internal/soca-science/pull/88 is merged

**Pull request closed without merging**
